# Generated by Django 4.1.2 on 2023-06-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=1, max_length=6, primary_key=True, serialize=False),
        ),
    ]
