# Generated by Django 4.1.2 on 2023-06-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_remove_producto_id_producto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
