# Generated by Django 4.1.2 on 2023-06-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_alter_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
