# Generated by Django 4.1.2 on 2023-06-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_remove_producto_id_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
