# Generated by Django 4.1.2 on 2023-06-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_alter_producto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
